name: OWHMe
version: 0.1
main: info.omgwtfhax.IGVindication1118Me.core.OWHMe
commands:
    me:
        description: displays a message under your name
        usage: /me <message>
    my:
        description: displays a possesive message under your name
        usage: /my <message>